# RENAME THIS FILE TO "config.ini"

# Global section: variables used by the server and the bot
# Server section: variables used only by the server
# Discord section: variables used only by the bot

[Global]
# Welcome to the main server configuration file!
# Below are all the configuration variables and their usage. Don't delete any of them!
# If you don't want to set something, delete "=" and the value
#
# Example: You don't want to set SUPPORTERS.
# SUPPORTERS variable looks like this: SUPPORTERS=username1, username2
# If you want to unset it, just edit it like this: SUPPORTERS

# By the way, these words are comments (every comment starts with "#") and you can make some or delete any of them!

# [---------- IGNORE THIS ----------]
# Database type
# Usage: DB_TYPE=<MySQL or SQLite>
# Note: If you set this to MySQL, check .env file for DB configuration.
# DB_TYPE=SQLite
# [---------------------------------]

# Usernames of chatbots in the server chat
# Usage: CHATBOT_USERNAMES=<list of usernames>
# Example: CHATBOT_USERNAMES=Grandmabot, Cookiebot
# Note: These usernames are reserved for chatbots, so users CANNOT choose these. If a user account with this username already exists, it will be renamed.
CHATBOT_USERNAMES

[Server]

# Server name
# Usage: SERVER_NAME=<text>
# Example: SERVER_NAME=OnlineClicker Server
SERVER_NAME=OnlineClicker Server

# Server password
# Usage: SERVER_PASSWORD=<text>
# Note: This is mostly useful only if you have a server that allows guests (players with no accounts).
SERVER_PASSWORD

# Whether guests (players with no accounts) should be allowed.
# Usage: GUESTS=<true or false>
GUESTS=false

# Server port
# Usage: PORT=<number>
# Example: PORT=24588
# Note: This is important, but you probably don't need to change it. You should probably learn more about ports!
PORT=8765

# Server WebSocket URL for players to connect to
# Usage: WS_URL=ws[s]://hostname:port
# Example: WS_URL=wss://onlineclicker.duckdns.org:8765
# Note: ws:// is for unsecured connections, wss:// is for secured connections (it's recommended to set up the secured one)
# Note #2: This will be sent to players when they are searching for servers.
WS_URL

# Server website (preferably a Discord server where users can create an account via the Discord bot)
# Usage: WEB=<link>
# Example: WEB=https://discord.gg/StJxMSc8kM
# Note: This will be sent to players when they are searching for servers.
WEB

# Maximum number of players on the server
# Usage: MAX_PLAYERS=<number>
# Example: MAX_PLAYERS=20
MAX_PLAYERS=16

# Maximum number of players in a single lobby
# Usage: MAX_IN_LOBBY=<number>
# Example: MAX_IN_LOBBY=10
MAX_IN_LOBBY=8

# Owners (by Discord user ID or username) (spaces are ignored)
# Usage: OWNERS=<list of IDs or usernames>
# Example: OWNERS=1217343439855812710, 1514272508503789681
# Another example: OWNERS=glitchedlime, bigbadwolf69
# Note: You CAN combine IDs and usernames! (like: OWNERS=1514272508503789681, glitchedlime)
# Note #2: Yes, this is my Discord user ID.
OWNERS=1217343439855812710

# Moderators (by Discord user ID or username) (spaces are ignored)
# The usage is the same as OWNERS
MODERATORS

# Supporters (by Discord user ID or username) (spaces are ignored)
# The usage is the same as OWNERS
SUPPORTERS

# Verified (by Discord user ID or username) (spaces are ignored)
# The usage is the same as OWNERS
VERIFIED=1217343439855812710

# Whether player chats should be logged
# Usage: LOG_MESSAGES=<true or false>
LOG_MESSAGES=true

# Whether the server shouldn't appear in the server browser.
# Usage: PRIVATE=<true or false>
PRIVATE=false

# Whether the server should run on localhost (closed network with your computer only)
# Usage: LOCALHOST=<true or false>
# Note: This is useful for testing.
LOCALHOST=false

[Discord]

# Discord moderator roles (by Discord role ID) (spaces are ignored)
# The usage is the same as OWNERS (no usernames!!)
# Note: Users with these roles can impose penalties on users. Server owner and admins are automatically added to mods.
MODROLES

# Discord server ID the bot is in
# Usage: DISCORD_SERVER_ID=<Role ID>
DISCORD_SERVER_ID=1514286817636257862

# (Optional) Registered role ID
# This role will be assigned when a player makes an account
# Usage: REGISTERED_ROLE_ID=<Role ID>
REGISTERED_ROLE_ID